version: '3'

services:
  tims-chatbot:
    build: .
    platform: linux/amd64
    image: tims-chatbot
    container_name: tims-chatbot
    command: uvicorn api.main:app --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000 
    restart: always
    environment:
      - NVIDIA_VISIBLE_DEVICES=all  